-- DRACONIS · BUZON PUBLICO DE COTIZACIONES
-- Ejecuta este archivo UNA SOLA VEZ en Supabase > SQL Editor.
-- No modifica las tablas anteriores de Draconis.

create table if not exists public.cotizaciones_web (
  id bigint generated by default as identity primary key,
  nombre text not null,
  whatsapp text not null,
  correo text not null,
  universidad text,
  nivel text not null,
  tipo_servicio text not null,
  casa text not null,
  materia text,
  modalidad text,
  ubicacion text,
  fecha_requerida date not null,
  hora_requerida time,
  presupuesto numeric,
  sin_limite_presupuesto boolean not null default false,
  descripcion text not null,
  origen text not null default 'web-draconis',
  estado text not null default 'nueva',
  created_at timestamptz not null default now(),
  constraint cotizaciones_web_estado_check
    check (estado in ('nueva','revisada','contactada','aceptada','descartada')),
  constraint cotizaciones_web_presupuesto_check
    check (presupuesto is null or presupuesto >= 0)
);

alter table public.cotizaciones_web enable row level security;

-- El visitante puede CREAR una solicitud, pero no leer solicitudes ajenas.
revoke all on table public.cotizaciones_web from anon, authenticated;
grant insert on table public.cotizaciones_web to anon;
grant usage, select on sequence public.cotizaciones_web_id_seq to anon;

-- Si la politica ya existe, la recreamos de forma segura.
drop policy if exists "public_can_create_quote" on public.cotizaciones_web;
create policy "public_can_create_quote"
on public.cotizaciones_web
for insert
to anon
with check (
  length(trim(nombre)) between 2 and 100
  and length(trim(whatsapp)) between 7 and 30
  and length(trim(correo)) between 5 and 160
  and length(trim(descripcion)) between 15 and 3000
  and estado = 'nueva'
  and origen = 'web-draconis'
);

-- No se concede lectura publica ni a usuarios autenticados desde el frontend.
-- La administracion puede revisar las solicitudes directamente en Supabase Studio.

comment on table public.cotizaciones_web is 'Buzon publico de cotizaciones de la web comercial de Draconis.';
